name: Linting

on:
  pull_request:
    branches:
      [main, master]
  push:
    branches:
      [main, master]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Run npm install
        run: npm install
      - name: Run linting
        run: npm run lint